/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_pegasus_rpc_LocalMemoryMappingJNI */

#ifndef _Included_org_apache_pegasus_rpc_LocalMemoryMappingJNI
#define _Included_org_apache_pegasus_rpc_LocalMemoryMappingJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_pegasus_rpc_LocalMemoryMappingJNI
 * Method:    getMappedBuffer
 * Signature: (IJJJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_apache_pegasus_rpc_LocalMemoryMappingJNI_getMappedBuffer
  (JNIEnv *, jclass, jint, jlong, jlong, jlong);

/*
 * Class:     org_apache_pegasus_rpc_LocalMemoryMappingJNI
 * Method:    getMappedBuffers
 * Signature: ([I[J[J[J)[Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobjectArray JNICALL Java_org_apache_pegasus_rpc_LocalMemoryMappingJNI_getMappedBuffers
  (JNIEnv *, jclass, jintArray, jlongArray, jlongArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
